# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yufan lu/OneDrive/Vivado Projects/CPU_START_FROM_0/CPU_START_FROM_0.srcs/sources_1/ip/ProgramMemory/ProgramMemory.xci
# IP: The module: 'ProgramMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yufan lu/OneDrive/Vivado Projects/CPU_START_FROM_0/CPU_START_FROM_0.srcs/sources_1/ip/ProgramMemory/ProgramMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProgramMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/yufan lu/OneDrive/Vivado Projects/CPU_START_FROM_0/CPU_START_FROM_0.srcs/sources_1/ip/ProgramMemory/ProgramMemory.xci
# IP: The module: 'ProgramMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yufan lu/OneDrive/Vivado Projects/CPU_START_FROM_0/CPU_START_FROM_0.srcs/sources_1/ip/ProgramMemory/ProgramMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ProgramMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
