set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property PACKAGE_PIN T18 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN R2 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN T1 [get_ports uart_rtl_0_txd]
